---
- name: BGP neighbor state event from Arista
  hosts: localhost
  sources:
   - ansible.eda.kafka:
       host: broker
       port: 9092
       topic: network
  rules:
   - name: BGP neighbor is down
     condition: event.body.fields.session_state == "IDLE"
     actions:
       - run_job_template:
           name: "EDA-Notify-Mattermost"
           organization: "Default"
           job_args:
             extra_vars:
               bgp_state: "{{ event.body.fields.session_state }}"
               bgp_prob_neighbor: "{{ event.body.tags.neighbor_address }}"
               bgp_timestamp: "{{ event.body.timestamp }}"
               bgp_error_type: "{{ event.body.tags.identifier }}"
