---
- name: BGP Change Observation
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Send notification message via Mattermost
      community.general.mattermost:
       delegate_to: localhost
       url: http://podman-host:8065
       api_key: "{{ MATTERMOST_API_TOKEN }}"
       attachments:
         - text: "!!!!!! ALERT !!!!!!"
           color: '#ff00dd'
           title: BGP ERROR
           fields:
            - title: Issue Detected
              value: "BGP Session: {{ bgp_state }}"
              short: true
            - title: Potential Problem
              value: "Problematic node/path: {{ bgp_prob_neighbor }}"
              short: true
            - title: Message
              value: "Event detected issue, human intervention is required, Dave"
              short: true
